"""Generate .streamlit/secrets.toml for Streamlit native auth from env vars.

Streamlit's st.login / st.user (OpenID Connect) reads its configuration
from .streamlit/secrets.toml, but on Render we only have environment
variables. This module renders the [auth] section from env vars. It is
idempotent: the file is only rewritten when its content changes, so it
does not trigger Streamlit reload loops.

Can be run directly (``python auth_secrets.py``) or imported and called
from app.py at startup.
"""

from __future__ import annotations

import os
from pathlib import Path

REQUIRED_VARS = (
    "GOOGLE_OAUTH_CLIENT_ID",
    "GOOGLE_OAUTH_CLIENT_SECRET",
    "AUTH_COOKIE_SECRET",
    "AUTH_REDIRECT_URI",
)

TEMPLATE = """# Auto-generated by auth_secrets.py — do not edit by hand.
[auth]
redirect_uri = "{redirect_uri}"
cookie_secret = "{cookie_secret}"
client_id = "{client_id}"
client_secret = "{client_secret}"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"
"""


def missing_auth_vars() -> list[str]:
    """Return the names of auth env vars that are not set."""
    return [v for v in REQUIRED_VARS if not os.environ.get(v)]


def ensure_auth_secrets() -> bool:
    """Write .streamlit/secrets.toml from env vars if all are present.

    Returns:
        True when the secrets file exists (written or already up to date),
        False when auth env vars are missing.
    """
    if missing_auth_vars():
        return False

    content = TEMPLATE.format(
        redirect_uri=os.environ["AUTH_REDIRECT_URI"],
        cookie_secret=os.environ["AUTH_COOKIE_SECRET"],
        client_id=os.environ["GOOGLE_OAUTH_CLIENT_ID"],
        client_secret=os.environ["GOOGLE_OAUTH_CLIENT_SECRET"],
    )

    secrets_path = Path(__file__).parent / ".streamlit" / "secrets.toml"
    secrets_path.parent.mkdir(exist_ok=True)
    if not secrets_path.exists() or secrets_path.read_text(encoding="utf-8") != content:
        secrets_path.write_text(content, encoding="utf-8")
    return True


if __name__ == "__main__":
    from dotenv import load_dotenv

    load_dotenv()
    if ensure_auth_secrets():
        print("Wrote .streamlit/secrets.toml")
    else:
        print(f"Missing env vars: {', '.join(missing_auth_vars())}")
        raise SystemExit(1)
